stages:

  train:
    cmd: python model/train.py
    deps:
      - model/train.py
    params:
      - model/train.py:
          - DATASET
          - N_FEATURES
          - RANDOM_STATE
    outs:
      - model/weights/model.pkl:
          cache: true
    metrics:
      - model/metrics.json:
          cache: false
    plots:
      - model/plots/confusion_matrix.csv:
          x: predicted
          y: actual
